version: '3'
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - 13301:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/dev/data/mysql-master:/var/lib/mysql
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - 13302:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/dev/data/mysql-slave:/var/lib/mysql
      - ./mysql-slave/mysql-slave.cnf:/etc/mysql/conf.d/my.cnf
