apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-album-pvc
  namespace: picup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3G
  storageClassName: 'nfs-client'