apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: node-reserved-ip-pool-1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.0-192.168.0.99
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: node-reserved-ip-pool-2
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.100-192.168.0.119
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ip-pool-1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.120-192.168.0.149
