version: '3'
services:
  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6379:6379
    volumes:
      - ~/dev/data/redis-data:/data
      - ~/dev/data/redis-data/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command:
      redis-server --save "" --appendonly no --databases 1 --maxmemory 256mb --maxmemory-policy allkeys-lru
    # AOF, RDB : none
    # database : only 1 namespace, default number of namespaces is 16
    deploy:
      resources:
        limits:
          memory: 300M
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ~/dev/data/rabbitmq:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password