image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.4.1-debian-11-r0

heapOpts: -Xmx1024m -Xms1024m

deleteTopicEnable: true
autoCreateTopicsEnable: true
logsDirs: /bitnami/kafka/data
maxMessageBytes: _1000012

numIoThreads: 8
numNetworkThreads: 3

numPartitions: 1
replicaCount: 1
nodeAffinityPreset:
  type: ""
  key: ""
  values: []

service:
  type: ClusterIP
  ports:
    client: 9092
    controller: 9093
    internal: 9094
    external: 9095
  nodePorts:
    client: ""
    external: ""
  clusterIP: ""
  loadBalancerIP: ""

persistence:
  enabled: true
  existingClaim: ""
  storageClass: nfs-client
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  annotations: {}
  labels: {}
  selector: {}
  mountPath: /bitnami/kafka

logPersistence:
  enabled: false

serviceAccount:
  create: true
  name: ""

kraft:
  enabled: true

zookeeper:
  enabled: false
