apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-server
  namespace: picup
  labels:
    app: storage-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-server
  template:
    metadata:
      labels:
        app: storage-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - storage-server
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: storage-server
          image: ghcr.io/ecsimsw/picup/api-storage:latest
          envFrom:
          - configMapRef:
              name: picup-common-config
          - configMapRef:
              name: storage-server-config
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-login-secret
