apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: audits-mongodb-sts
  namespace: mymarket
spec:
  serviceName: audits-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: audits-mongodb
  template:
    metadata:
      labels:
        app: audits-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.1
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: audits-mongodb-secret
          volumeMounts:
            - name: audits-mongodb-persistent-storage
              mountPath: /data/db
      imagePullSecrets:
        - name: docker-registry-secret
  volumeClaimTemplates:
    - metadata:
        name: audits-mongodb-persistent-storage
      spec:
        storageClassName: nfs-client
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 10Gi
