server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: picup
    static_configs:
      - targets:
          - picup-application
        labels:
          job: application
          __path__: /logs/application/*.log
      - targets:
          - picup-s3
        labels:
          job: s3
          __path__: /logs/s3/*.log
