apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-album-hpa
  namespace: picup
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-album
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: ContainerResource
      containerResource:
        name: memory
        container: application
        target:
          type: Utilization
          averageUtilization: 80