apiVersion: batch/v1
kind: CronJob
metadata:
  name: server-batch
  namespace: picup
spec:
  schedule: "*/1 * * * *"     # every minute
  concurrencyPolicy: Forbid   # skip if job already exists
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/role: internal-app
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-picup: picup/common
            vault.hashicorp.com/agent-inject-template-picup: |
              {{- with secret "picup/common" -}}
              {{- range $k, $v := .Data }}
              export {{ $k }}={{ $v }}
              {{end}}{{end}}
        spec:
          containers:
            - name: server-batch
              image: ghcr.io/ecsimsw/picup/server-batch:latest
              imagePullPolicy: Always        # check container hub if image not present, 'name+tag+digest'
              volumeMounts:
                - name: picup-data
                  mountPath: /ext-data       # READ private_key.pem
#              envFrom:
#                - secretRef:
#                    name: server-common-secret
          restartPolicy: Never
          volumes:
            - name: picup-data
              persistentVolumeClaim:
                claimName: server-album-pvc