{
 "title": "picup",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Memory-usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API server - memory usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\", instance=\"host.docker.internal:52082\"}) * 100) / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"host.docker.internal:52082\", area=\"heap\"})",
     "legendFormat": "api-member"
    },
    {
     "expr": "(sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\", instance=\"host.docker.internal:52083\"}) * 100) / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"host.docker.internal:52083\", area=\"heap\"})",
     "legendFormat": "api-storage"
    },
    {
     "expr": "(sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\", instance=\"host.docker.internal:52084\"}) * 100) / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"host.docker.internal:52084\", area=\"heap\"})",
     "legendFormat": "api-album"
    }
   ]
  },
  {
   "title": "API member - JVM heap",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"host.docker.internal:52082\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"host.docker.internal:52082\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "API storage - JVM heap",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"host.docker.internal:52083\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"host.docker.internal:52083\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "API album - JVM heap",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"host.docker.internal:52084\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"host.docker.internal:52084\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Request count per 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (ceil(increase(http_server_requests_seconds_count{instance=\"host.docker.internal:52082\"}[1m])))",
     "legendFormat": "api-member"
    },
    {
     "expr": "sum by(instance) (ceil(increase(http_server_requests_seconds_count{instance=\"host.docker.internal:52083\"}[1m])))",
     "legendFormat": "api-storage"
    },
    {
     "expr": "sum by(instance) (ceil(increase(http_server_requests_seconds_count{instance=\"host.docker.internal:52084\"}[1m])))",
     "legendFormat": "api-album"
    }
   ]
  },
  {
   "title": "Server error response count per 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (ceil(increase(http_server_requests_seconds_count{instance=\"host.docker.internal:52082\", status!=\"200\"}[1m])))",
     "legendFormat": "api-member"
    },
    {
     "expr": "sum by(instance) (ceil(increase(http_server_requests_seconds_count{instance=\"host.docker.internal:52083\", status!=\"200\"}[1m])))",
     "legendFormat": "api-storage"
    },
    {
     "expr": "sum by(instance) (ceil(increase(http_server_requests_seconds_count{instance=\"host.docker.internal:52084\", status!=\"200\"}[1m])))",
     "legendFormat": "api-album"
    }
   ]
  },
  {
   "title": "Api member - HTTP duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_sum{instance=\"host.docker.internal:52082\"}[1m])) / avg(rate(http_server_requests_seconds_count{instance=\"host.docker.internal:52082\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{instance=\"host.docker.internal:52082\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "API storage - HTTP duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"host.docker.internal:52083\"}[1m])) / sum(rate(http_server_requests_seconds_count{instance=\"host.docker.internal:52083\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{instance=\"host.docker.internal:52083\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "API album - HTTP duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"host.docker.internal:52084\"}[1m])) / sum(rate(http_server_requests_seconds_count{instance=\"host.docker.internal:52084\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{instance=\"host.docker.internal:52084\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"host.docker.internal:52082\"}[1m]) / rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"host.docker.internal:52082\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}