apiVersion: v1
kind: Service
metadata:
  labels:
    app: member-server
  name: member-server-svc
  namespace: picup
spec:
  ports:
    - port: 8082
      name: http
      protocol: TCP
      targetPort: 8082
  selector:
    app: member-server