apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-server
  namespace: picup
  labels:
    app: member-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-server
  template:
    metadata:
      labels:
        app: member-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - member-server
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: member-server
          image: ghcr.io/ecsimsw/picup/api-member:latest
#          java -Xms=256m -Xmx=1536m -XX:NewSize=32m -XX:MaxNewSize=512m -XX:NewRatio=2 -XXSurvivorRatio=8
#          args: ["-Xms=256m", "-Xmx=1536m", ]
          envFrom:
          - configMapRef:
              name: common-config
          - configMapRef:
              name: member-server-config
          ports:
            - containerPort: 8082
          startupProbe:
            httpGet:
              path: /
              port: 8082
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            failureThreshold: 20
            periodSeconds: 120
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-login-secret
