version: '2'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ~/redis-data/data:/data
      - ~/redis-data/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: mymarket-zookeeper-container
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    container_name: mymarket-kafka-container
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

#  mongodb:
#    image: mongo:6.0.1
#    container_name: mymarket-audits-mongodb-container
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    volumes:
#      - ~/mongo-data:/data/db
#
#  mysql:
#    image: mysql:8.0
#    container_name: mymarket-products-mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ~/mysql-data:/var/lib/mysql
#

