apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: products-mysql-sts
  namespace: mymarket
spec:
  serviceName: products-mysql
  replicas: 1
  selector:
    matchLabels:
      app: products-mysql
  template:
    metadata:
      labels:
        app: products-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: products-mysql-secret
          volumeMounts:
            - name: products-mysql-persistent-storage
              mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: docker-registry-secret
  volumeClaimTemplates:
    - metadata:
        name: products-mysql-persistent-storage
      spec:
        storageClassName: nfs-client
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 10Gi
