apiVersion: v1
kind: Service
metadata:
  name: storage-api
  namespace: picup
spec:
  selector:
    app: storage-api
  ports:
    - protocol: TCP
      port: 30884            # port of service
      targetPort: 8084       # to pod
      nodePort: 30884
  type: NodePort