helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller

helm upgrade --install --namespace actions-runner-system --create-namespace \
--set=authSecret.create=true \
--set=authSecret.github_token=${GITHUB_PAT_TOKEN} \
--wait actions-runner-controller actions-runner-controller/actions-runner-controller
