version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/route-api.conf:/etc/nginx/conf.d/route-api.conf
      - ./config/route-admin.conf:/etc/nginx/conf.d/route-admin.conf
    ports:
      - "8520:80"       # for api
      - "8531:3000"     # for grafana
      - "8532:3000"     # for prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"