version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/routing.conf:/etc/nginx/conf.d/routing.conf
    ports:
      - "8080:80"
    environment:
#      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    extra_hosts:
      - "host.docker.internal:host-gateway"