env:
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdout
  proxy_error_log: /dev/stderr
  admin_error_log: /dev/stderr

image:
  repository: kong
  tag: "3.3"

admin:
  enabled: false

status:
  enabled: true

proxy:
  # Enable creating a Kubernetes service for the proxy
  enabled: true
#  type: NodePort
  type: LoadBalancer
  loadBalancerClass:

  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
#    nodePort: 32080

  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443
    parameters:
      - http2

ingressController:
  enabled: true
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "2.10"
