DELIMITER $$
DROP PROCEDURE IF EXISTS BASIC_INSERT;
CREATE PROCEDURE BASIC_INSERT()
BEGIN
 DECLARE i INT DEFAULT 1;
 DECLARE maxIndex INT DEFAULT 100000;
 WHILE( i < maxIndex) DO
  INSERT INTO MEMBER(USERNAME, PASSWORD)
  VALUES(
   CONCAT("user-", i),
   UUID()
  );
  SET i = i+1;
END WHILE;
END $$
DELIMITER ;