CREATE TABLE MEMBER(ID BIGINT, USERNAME VARCHAR(50), PASSWORD VARCHAR(50));
CREATE TABLE ALBUM(ID BIGINT, USERID BIGINT, TITLE VARCHAR(50), DESCRIPTION VARCHAR(100));
CREATE TABLE PICTURE(ID BIGINT, ALBUMID BIGINT, DESCRIPTION VARCHAR(100));