# https://github.com/hashicorp/vault-helm/blob/main/values.yaml

global:
  # External vault server address for the injector and CSI provider to use.
  # Setting this will disable deployment of a vault server.
  externalVaultAddr: "http://192.168.0.4:8200"

injector:
  enabled: "true"
  # Configures the port the injector should listen on
  port: 8200
  # Deprecated: Please use global.externalVaultAddr instead.
  externalVaultAddr: "http://192.168.0.4:8200"
  agentImage:
    repository: "hashicorp/vault"
    tag: "1.16.1"
  agentDefaults:
    cpuRequest: "50m"
    memRequest: "64Mi"