apiVersion: v1
kind: Service
metadata:
  name: test-nginx-np
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 30883          # port of service
      targetPort: 80     # to pod
      nodePort: 30883      # node's port
  type: NodePort