apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-album
  namespace: picup
spec:
  selector:
    matchLabels:
      app: server-album
  replicas: 1
  template:
    metadata:
      labels:
        app: server-album
    spec:
      containers:
        - name: server-album
          image: ghcr.io/ecsimsw/picup/server-album:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8084