global:
  scrape_interval: 15s     # scrap interval, default = 1m
  scrape_timeout: 15s      # scrap request timeout, default = 10s
  evaluation_interval: 2m  # rule evaluation interval, default = 1m
  query_log_file:          # prometheus query logs
  external_labels:
    monitor: ''

scrape_configs:
  - job_name: 'storage-server-jvm-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.101:30884' ]
  - job_name: 'member-server-jvm-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.101:30883' ]
  - job_name: 'nginxlog-exporter'
    static_configs:
      - targets: [ "host.docker.internal:4040" ]