apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-ations-runner-hpa-mymarket
  namespace: actions-runner-system
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: github-action-runner-mymarket
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'     # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
      scaleDownThreshold: '0.25'   #  The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
      scaleUpFactor: '2'           # The scale up multiplier factor applied to desired count
      scaleDownFactor: '0.5'       # The scale down multiplier factor applied to desired count
