apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-action-runner-mymarket
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: ecsimsw/A-to-Z
      labels:
        - ecsimsw-ga
