apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-ip-pool-1

# MetalLB는 L2 네트워크(ARP/NDP)와 L3 네트워크(BGP)로 밸런싱한다.
# (Boarder gateway protocol : 서로 다른 조직의 네트워크나 ISP를 연결할 떄 사용)
# (AS : Autonomous System, 동일한 라우팅 정책을 갖고 있는 집단 단위, 모든 네트워크 노드가 아닌 AS내의 도달 정보만 갖으면 되도록.)
