server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: piup
    static_configs:
      - targets:
          - picup
        labels:
          job: application-warn
          __path__: /logs/*log
