apiVersion: v1
kind: Service
metadata:
  labels:
    app: album-server
  name: album-server-svc
  namespace: picup
spec:
  ports:
    - port: 8084
      name: http
      protocol: TCP
      targetPort: 8084
  selector:
    app: album-server