global:
  scrape_interval: 15s     # scrap target의 기본 interval을 15초로 변경 / default = 1m
  scrape_timeout: 15s      # scrap request 가 timeout 나는 길이 / default = 10s
  evaluation_interval: 2m  # rule 을 얼마나 빈번하게 검증하는지 / default = 1m
  query_log_file:     # prometheus의 쿼리 로그들을 기록, 없으면 기록안함
  external_labels:
    monitor: ''       # 표시 라벨

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'jvm-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    scrape_interval: 15s      # global에서 default 값을 정의해주었기 떄문에 안써도됨
    scrape_timeout: 15s       # global에서 default 값을 정의해주었기 떄문에 안써도됨
    honor_labels: false       # 옵션 - 라벨 충동이 있을경우 라벨을 변경할지설정(false일 경우 라벨 안바뀜) | default = false
    honor_timestamps: false   # 옵션 - honor_labels이 참일 경우, metrics timestamp가 노출됨(true일 경우) | default = false
    scheme: 'http'            # 옵션 - request를 보낼 scheme 설정 | default = http
    params:
      user-id: [ 'ecsimsw@email.com' ]