Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-22.04"
    node1.vm.network "public_network", bridge: "wlo1", ip: "192.168.0.101"
    node1.vm.hostname = "node1"
    node1.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 1
    end
  end
end