apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-server
  namespace: picup
  labels:
    app: album-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: album-server
  template:
    metadata:
      labels:
        app: album-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - album-server
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: album-server
          image: ghcr.io/ecsimsw/picup/api-album:latest
          envFrom:
          - configMapRef:
              name: common-config
          - configMapRef:
              name: album-server-config
          ports:
            - containerPort: 8084
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            failureThreshold: 20
            periodSeconds: 120
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-login-secret
