name: directory list
on:
  workflow_dispatch:
  push:
    branches:
      - release
jobs:
  server-application:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name : test
        run: |
          cd ./server-api
          chmod +x ./gradlew
          ./gradlew :api-album:test
          ./gradlew :api-member:test
          ./gradlew :api-storage:test
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
          logout: true
      - name: Build and push
        run: |
          cd ./server-api
          chmod +x ./gradlew
          version=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          ./gradlew :api-album:jib -Djib.to.tags=latest,${version}
          ./gradlew :api-member:jib -Djib.to.tags=latest,${version}
          ./gradlew :api-storage:jib -Djib.to.tags=latest,${version}

