apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: storage-api-hpa
  namespace: picup
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: ContainerResource
      containerResource:
        name: memory
        container: application
        target:
          type: Utilization
          averageUtilization: 80